### ISSUE TITLE
TypeError: 'UUID' object is not iterable

### ISSUE THREAD

**Issue by jabowery** [team-telnyx/demo-appointment-reminders-python#1]
```
(sms.service) delegate@delegate:~/sms.service$ python schedule_meeting_server.py 
 * Serving Flask app 'schedule_meeting_server' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://127.0.0.1:5010/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 818-602-794
127.0.0.1 - - [24/Aug/2021 21:33:32] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/delegate/anaconda3/envs/sms.service/lib/python3.9/site-packages/flask/app.py", line 2088, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/delegate/anaconda3/envs/sms.service/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.handle_exception(e)
  File "/home/delegate/anaconda3/envs/sms.service/lib/python3.9/site-packages/flask/app.py", line 2069, in wsgi_app
    ctx.push()
  File "/home/delegate/anaconda3/envs/sms.service/lib/python3.9/site-packages/flask/ctx.py", line 404, in push
    self.session = session_interface.open_session(self.app, self.request)
  File "/home/delegate/anaconda3/envs/sms.service/lib/python3.9/site-packages/flask/sessions.py", line 353, in open_session
    s = self.get_signing_serializer(app)
  File "/home/delegate/anaconda3/envs/sms.service/lib/python3.9/site-packages/flask/sessions.py", line 343, in get_signing_serializer
    return URLSafeTimedSerializer(
  File "/home/delegate/anaconda3/envs/sms.service/lib/python3.9/site-packages/itsdangerous/serializer.py", line 104, in __init__
    self.secret_keys: _t.List[bytes] = _make_keys_list(secret_key)
  File "/home/delegate/anaconda3/envs/sms.service/lib/python3.9/site-packages/itsdangerous/signer.py", line 64, in _make_keys_list
    return [want_bytes(s) for s in secret_key]
TypeError: 'UUID' object is not iterable
$ conda list |egrep 'telnyx|flask|celery|redis'
celery                    5.1.2              pyhd8ed1ab_0    conda-forge
flask                     2.0.1              pyhd8ed1ab_0    conda-forge
redis                     3.5.3                    pypi_0    pypi
telnyx                    1.4.0              pyhd8ed1ab_0    conda-forge
```

**Comment by jabowery** [comment]
My attempt at a fix seems to work:
```
#import uuid
import os
import binascii
from datetime import datetime, timedelta

import telnyx
from celery import Celery
from flask import Flask, request, render_template, flash

app = Flask(__name__)
#app.secret_key = uuid.uuid4()
app.secret_key = binascii.hexlify(os.urandom(20)).decode()
print(f'secret key: {app.secret_key}')
app.config.from_pyfile('config_file.cfg')

```
